### ISSUE TITLE
ICEHOOKS AppVar

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#101]
Could someone attach the newest version of the ICEHOOKS AppVar here? I don't have the ability to compile it from source. Thanks

**Comment by PeterTillema** [comment]
First of all, that is not an issue; secondly, definitely not in the ICE repo but rather the ICEHOOKS repo. Thirdly, you can just ask on Cemetech or #cemetech and people are happy to help you. And lastly, whatever, here is it: https://ufile.io/xo17p

**Comment by calclover2514** [comment]
Sorry, I did not realize that they were separate or that I could access them from cemetech. Thanks for attaching it though.

P.S. I don't know why I posted this as an issue. I was in a hurry to get somewhere and wasn't thinking straight. Sorry
