### ISSUE TITLE
Tilemapping doesn't work on ICE v2.3

### ISSUE THREAD

**Issue by Ti64CLi** [PeterTillema/ICE#102]
I tried to make mi own tilemap, and my program only displayed me a blank screen, then my calc rebooted
Then I tried to launch TWHGAME, and my calc rebooted. :(

**Comment by Ti64CLi** [comment]
Still doesn't work. But now, when I launch my program with my own tilemap, the screen isn't blank but with some weird things, then my calc reboot :(

**Comment by PeterTillema** [comment]
Did you build the latest ICE and tried that version? Didn't you forget to transfer also `LEVELS.8xv` and `TILES.8xv` to the calc? The game will indeed crash if they are not present.

**Comment by Ti64CLi** [comment]
Yes I built the latest ICE. 
But you're right, I don't have LEVELS.8xv and TILES.8xv anymore. I'll try again

**Comment by Ti64CLi** [comment]
Yes, it's now working.
But what are the DRAW_HEIGHT ans DRAW_WIDTH for DefineTilemap?

**Comment by Ti64CLi** [comment]
OK thanks, it's now working perfectly :)

**Comment by Ti64CLi** [comment]
I don't know if it's the right place, but what are the differences between TilePtr ans TilePtrMapped?

**Comment by PeterTillema** [comment]
> I don't know if it's the right place, but what are the differences between TilePtr and TilePtrMapped?

No it's not. That what #cemetech and #icedev is for. Anyway, the difference is whether you want the pointer to get from pixels or tiles.
