### ISSUE TITLE
Detect and DetectVar

### ISSUE THREAD

**Issue by beckadamtheinventor** [PeterTillema/ICE#103]
I have been making a program in ICE that requires Detect (or DetectVar)
Problem: neither of them work. They both stop the program (or so far as I can see) every time I use them. Note that I have no variables that should be detected. (see "Lbl DETECTX" for the routine)
I have attempted to debug the program with pauses but to no avail. I have resolved that it is a problem with Detect and DetectVar. (I have tried both, and both have the same result)
I know that it is stopping the program, due to the screen after the program is run (the screen goes to  half-res)

I hope that this can be resolved, or an alternative be made, at your earliest convenience; this is an ICE-breaking bug, and as I said, neither of these routines work at this time.

[SINCESRC.zip](https://github.com/PeterTillema/ICE/files/2456963/SINCESRC.zip)

**Comment by PeterTillema** [comment]
Can you give me a few appvars with the right header?

**Comment by PeterTillema** [comment]
I can't reproduce this with the latest built ICE. It just stays at a black screen until I press `[ENTER]` and then it properly returns to the OS. Do you have the latest ICE build?

**Comment by beckadamtheinventor** [comment]
I have ICE 2.2.0. I have tried RAM resetting.
The appvar header is in the variable "HEADER"

**Comment by calclover2514** [comment]
ICE v2.3 doesn't have this issue. Try building from source or getting an older v2.3 build here: [https://ufile.io/dgtp8](https://ufile.io/dgtp8)
