### ISSUE TITLE
Hooks not installing

### ISSUE THREAD

**Issue by beckadamtheinventor** [PeterTillema/ICE#105]
So I got a new calculator recently, and it came with OS 5.3.1. I was able to downgrade succesfuly to 5.3.0.
My problem is that, no matter how many times I run ICE, none of the hooks install.
I am using ICE 2.2.0.

**Comment by PeterTillema** [comment]
You need the latest ICE and ICEHOOKS from Github, these should work properly.

**Comment by jcgter777** [comment]
How come the hooks stop working after a while?
Suspects: Cesium, TI-Boy, BOSShell
