### ISSUE TITLE
Exiting on getKey?

### ISSUE THREAD

**Issue by beckadamtheinventor** [PeterTillema/ICE#106]
I have been using the newest ICE (2.3.0) and it appears to exit the program whenever I use this code:
`Lbl K
Repeat getKey->K
End
Return`
I have tried
`Lbl K
Repeat K
getKey->K
End
Return`
which should be the same. Both exit upon calling this routine.
This is an ICE-breaking bug, as I'm sure you can see.

**Comment by PeterTillema** [comment]
I need more code, since I can't replicate this.

**Comment by beckadamtheinventor** [comment]
Yeah... I can't really figure out precisely where my program isn't compiling properly, so Idk what is going wrong.
