### ISSUE TITLE
ICE Input Command Not Working Correctly

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#109]
"Input A" doesn't work correctly, but "Input "?",A does.
"Input "?",Str1" doesn't work and "Input "?",A:Copy(Str1,A,len)" doesn't work (len can equal any number, it still won't work)
For instance, if I use "Input "?",A:Copy(Str1,A,len)" and input "BEN", ICE returns "GRASS+2?" (WHAT???!!!)
Please help.
Thanks

**Comment by beckadamtheinventor** [comment]
Are you using the full graphics? "det(0"?
If so, this command _will not work for that purpose_
You need to allocate memory first to use "Copy(", because that routine only moves bytes from one memory adress to another. Also, try "length(A)" for the "len" argument

Hope this helps

**Comment by calclover2514** [comment]
I am not using graphics. Also, could you please tell me how to allocate memory for "Copy("?
Thanks

**Comment by Ti64CLi** [comment]
You can use the Alloc( command, which can be find in the Trace menu ;)

**Comment by calclover2514** [comment]
I thought that you would say that. However, I cannot find any documentation on any of the commands. Also, ""Ben"->A:Copy(Str1,A,len)" does work without "Alloc(". Please help.

**Comment by PeterTillema** [comment]
What "doesn't work"? `Input A` correctly sets the inputted value to A for me, as well as `Input "A=",A`. Just remember the input is treated as a number, not a string.
