### ISSUE TITLE
Unable to read from strings

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#110]
I have tried every possible way to read from and write to actual OS strings (the ones that keep their values after a program is done executing), but I cannot seem to actually get them to return their actual values.
I don't know if this is an issue or if I just don't know how.
Any help would be appreciated.
Thanks

**Comment by PeterTillema** [comment]
```
CloseAll
Open('Str0',"r+",4->SLOT
```
This works for me, as long as Str0 already exists (because mode r+).
