### ISSUE TITLE
Run Button in ICE not working

### ISSUE THREAD

**Issue by wizardhws** [PeterTillema/ICE#112]
I just installed the latest version 2.2.1 of ICE and I have version 5.3.1.0058 firmware on my TI 84 plus ce.  When I press BUILD the src compiles correctly, but when I press RUN in  ICE it clears ram.
If I do a build and then quit ICE, the program runs fine.

Also the read me file says there should be three files to sent to he calculator but only two are included, the debug file is not included.

Otherwise, so far everything else appears to run as advertised. Even with RUN not working it is a great program.

Herman Schoob  schoobh1955@gmail.com

**Comment by PeterTillema** [comment]
I can confirm; the C startup routine changed, and I only changed my routine for going to the editor, not running the program, causing the stack to be messed up.
