### ISSUE TITLE
Output and Disp unexpected behaviour

### ISSUE THREAD

**Issue by Xenoxis** [PeterTillema/ICE#115]
Hello, it seems that Output and Disp have an unexpected behaviour with variables.
With that code : 
```
:ClrHom
:0->A
:Disp A
```
or 
```
:ClrHom
:0->A
:Output(1,1,A
```

It's output correctly the variable but shifted to the right (about 5-6 spaces characters).
I've seen that there's already an issue about that, but i'm with the latest version of ICE Compiler (2.2.1) that i've found pre-compiled on [Cemetech Archives](https://www.cemetech.net/programs/index.php?mode=file&path=/84pce/asm/programs/ICECompiler.zip).

**Comment by PeterTillema** [comment]
Yes, that's indeed the behaviour of these commands. It does that because it's kinda hard to know of how many digits a number exists, so it always uses 8 spaces minus the amount of digits in front of the string. (8 spaces because max number (16777216) has 8 digits).
