### ISSUE TITLE
LibGraphx bug

### ISSUE THREAD

**Issue by Xenoxis** [PeterTillema/ICE#116]
Hello, i've a made a programme that change the Screen's Brightness with a simple menu.
It seem to me a bit useless to use the graphics mode because i just needed to display some text.
And, for the disign, i wanted to fill the screen in white without use the `Begin()` method, like :
```
:iTest

:Lbl Init
:det(5,255
...
```

ICE has compiled it without errors, which surprised me, but anyway : the programme works well !
Then i turn off my calculator, i turn it on and try to open my programme, but it crashed and reset the RAM.
And from now, if i don't go to ICE before open my programme, it crash. So i deducted that ICE initialise the Graphics librairie without stop it, that allow to me to use some functions under the default screen mode.

Then i have 2 requests : 
- Add a function to initialise the Graphics librairie without go to the Graphics screen mode.
- There's a bug in ICE ?

**EDIT : When i add `det(0` and directly after `det(1`, the bug didn't appears and the programme run fine without crashing and/or resetting RAM**

**Comment by PeterTillema** [comment]
There is no bug in ICE, you should *always* initialize the screen with `det(0` without any exception. Besides cleaning the screen to white it sets a few (internal) variables which are important.

**Comment by Xenoxis** [comment]
So to clear the screen or use any others functions that normally use the graphics screen mode  (and those can work properly in the normal screen mode) i must do 
```
:det(0
:det(1

code and functions
```

That's a bit ugly, isen't it ?

**Comment by Xenoxis** [comment]
Yes, but `det(0)` fill the screen, and set the font size to 8. But i've seen that is possible to use `FillScreen()` in the default screen mode (as the OS shell is set)  if you initialize one time the graphics lib, and directly after you leave it, i have noticed that you can still use `FillScreen()`, until you turn off your caculator.

The code is : 
```
:det(0)
:det(1)
:FillScreen(255
```
If I'm wrong, please details to me why this work even you turn off the libs (or when you turn one time on the libs) and why when you turn off your calculator, you can't use `FillScreen()` until you do the thing that i've described.
Thanks in advance for your reply.
