### ISSUE TITLE
Add custom string variable names & allow Ans to be a string.

### ISSUE THREAD

**Issue by TheLastMillennial** [PeterTillema/ICE#119]
It would be very useful to be able to store strings into custom variables rather than preset StringVars 
Example
"Hello"+"World"->VARIABLE
(VARIABLE should now have "HelloWorld" stored in it) also allow
VARIABLE+"Test"->VARIABLE
(VARIABLE should now have "HelloWorldTest" stored in it).
It would be necessary that sub(), length(), and inString() work with the custom string variable names.

It would also be useful if ICE could allow Ans to be recalled as a string rather than setting Ans to 0 if a string is stored in it. This would be useful for making ICE programs that are specifically designed to be a subprogram. Instead of eating up a StringVar, the program could simply check for the last string stored in Ans.

**Comment by PeterTillema** [comment]
The first one is definitely useful, and some sort of that is already implemented (you can store a string to a variable IIRC). The second one seems impossible to me: what would A be in `Ans->A`? Would it be a string? Would it be an integer? The types are declared at compile-time, not run-time.

**Comment by calclover2514** [comment]
@TheLastMillennial Said:
> It would also be useful if ICE could allow Ans to be recalled as a string rather than setting Ans to 0 if a string is stored in it.
This is already possible in ICE.
Just use OpenVar('Ans',"r",0) making sure to use single quotes, and access it like an AppVar.

**Comment by PeterTillema** [comment]
After further thinking, the first option is also impossible. How would I know if A is a string or a number? And what about `A+B`, are they both numbers or strings or whatever? I can't know, especially if it's after a Lbl or in a loop. calclover suggested the best way to use Ans as a string, so use that if possible.
