### ISSUE TITLE
Using the string "DEAD" causes the compiler to give an error

### ISSUE THREAD

**Issue by bailwillharr** [PeterTillema/ICE#120]
This is a very strange and specific issue. If you try to display or in any way manipulate the string "DEAD". the compiler gives the error: 'Warning! string has been automatically squished!'.
This error does not come up when using any other string. Although the program compiles, the results when running the program are very unpredictable.
Here's an example of this happening:
![dead](https://user-images.githubusercontent.com/13090559/52179572-26433700-27d4-11e9-9cbc-4c2c78799828.png)
Here is what should happen (substituting DEAD with HEAD as it works as expected):
![head](https://user-images.githubusercontent.com/13090559/52179578-32c78f80-27d4-11e9-9558-bcff167ca07e.png)
Why would such an error ever occur just because I used the string "DEAD"? I'd have to guess it has something to do with the compiler's compression/optimization algorithms.

**Comment by LAX18** [comment]
I believe this has to do with all of the characters of "DEAD" being valid hexadecimal characters (A-F). This causes ICE to compress it.

**Comment by Ti64CLi** [comment]
If you want to store "DEAD" in a string, you can use the single quote ' instead of the double quote ".
Or, you can add an other character which is not an hexadecimal characters (0-9 and A-F) like:

"DEAD " (a bank space)
