### ISSUE TITLE
Update list-based variable maximum size

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#131]
I believe that the maximum list-based variable (list, sprite, string, etc.) size should be one of the following:
1. 65,536 bytes (max AppVar size)
2. 65,538 bytes (max possible sprite size)

People would have to be more careful with variable allocation, but it would make many routines way easier.

**Comment by PeterTillema** [comment]
No, that doesn't make any sense, since then you only have around 3000 bytes left for dynamic allocation. Plus, there is in fact no size limit for lists, it's just that I defined L2 to be 2000 more than L1, but that doesn't mean `L1(2000)` doesn't work.
