### ISSUE TITLE
Unexplainable Bug

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#132]
If I create a 64 byte list and attempt to access it as a 8x8 matrix (with `*{LIST+(X*7)+Y}`), the numbers marked with a 0 work fine, but the numbers marked with the same letter mirror each other:
(Example: If you change one `A`, the other one changes as well)
```
0,A,B,C,D,E,F,G
0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0
A,B,C,D,E,F,G,0
```
I don't know why this is happening, but it makes writing a matrix-based game impossible.

P.S. This happens with lists/matrices of all lengths and sizes, and just follows the pattern

**Comment by PeterTillema** [comment]
Y needs to be multiplied by 8, not X by 7, i.e. `*{LIST+(Y*8)+X}`.

**Comment by calclover2514** [comment]
Thank you. I see that now (although I wanted X & Y switched)
