### ISSUE TITLE
Better Concatenation Modifier

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#135]
As concatenation is in ICE, it can only do `Str+Str`, `Str+"SOMETHING"`, and `"SOMETHING"+"SOMETHING"`
It would be extremely useful if you could extend concatenation to lists/strings stored in variables.
Ex.
```
Alloc(3)->A
Alloc(3)->B
Alloc(6)->C
1->*{A+1}
128->*{B+2}
A+B->C

C should now equal {0, 1, 0, 0, 0, 128}
```
\- or -
```
"Hello"->A
"World"->B
A+" "+B->C

C should now equal "Hello World"
```
This could raise some problems using the `+` modifier, as it also adds variables, so if this were to be implemented, a separate concatenation modifier might need to be added.

**Comment by PeterTillema** [comment]
This is sadly impossible. In your example, how do you know the "size" of A? It's just a pointer, and a pointer is a number, whereas a variable is a number too. Same with variable strings, they are all pointers. Doing something like
```
13000000->A
13123456->B
A+B->C
```
behaves the same, although those are numbers and not "lists". A separate modifier won't help, as we still don't know the size.

**Comment by PeterTillema** [comment]
Yes. What about elements with value 0 in it? Then the next elements are being cleared out. Oh, btw, this is just a Concat( routine you wrote, which is basically the same as `Copy(A+length(A),B,length(B`, except you write it to another location (which is what `+` does too). Even
```
A->Str1
B->Str2
Str1+Str2->Str3
Str3->C
```
would work.
