### ISSUE TITLE
Fatal flaw in ICE. Needs Urgent Fix!

### ISSUE THREAD

**Issue by UDXS** [PeterTillema/ICE#144]
Got ya! There is no fatal flaw.

Happy Birthday P_T!

The only gift I have for you is the only gift you need:
Copious amounts of virtual cake
`🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂🎂`

**Comment by beckadamtheinventor** [comment]
:open_mouth:  Happy Birthday!!! :smiley: :+1:

**Comment by PeterTillema** [comment]
Closing this, as it's not relevant anymore :(
