### ISSUE TITLE
Label names sometimes overlap

### ISSUE THREAD

**Issue by PeterTillema** [PeterTillema/ICE#19]
Example:

Goto ABC
code
Lbl ABC
code
Lbl ABCD

In this case, Goto ABC actually goes to ABCD.

**Comment by Pieman7373** [comment]
How much does this happen? Would it happen if only 2 letters in the menu name are the same? Is there a way to know for sure if/when this will happen?

**Comment by PeterTillema** [comment]
Fixed with 352bd38 .
