### ISSUE TITLE
Different Output Commands' Issues + Few Others

### ISSUE THREAD

**Issue by LemonJuiz** [PeterTillema/ICE#23]
### **[On TI-84+CE]**
The program 
```
iTEST
Repeat K=15
getKey->K
Disp K
End
```
compiles and runs fine (albeit a bit wonky as Disp seems to only print in the first result section on the far right and doesn't display anything when using a string), but this program: 
```
iTEST
Repeat K=15
getKey->K
Output(1,1,K
End
```
compiles but when run it never outputs anything and just ends immediately. Even removing the Repeat loop does nothing to help. 
Trying to use `det(17,K` in the same situation (replacing line 4) ***clears RAM***, so some error handling needs to be put in place there. Attempting to put anything inside of `toString(value[, format]` will throw a `Invalid arguments!` error also. `det(15,K,2` (not in given commands.html but in [TRACE] menu) and `det(16,K,2` writes presumably to the screen buffer as the screen fills up with the pixel pattern `black-black-green`.
These issues make it difficult to output anything to the Home screen in my experience.
##### Issues listed:
* `Disp` does not move cursor when displaying numbers and displays nothing except 2 blank lines with strings
* `Output` seems to end program early when reached
* `det(17 (PrintString)` crashes calculator
* `toString(` throws compilation errors
* `det(15 (PrintInt)` is not listed in given commands.html and writes to screen buffer
* `det(16 (PrintUInt)` writes to screen buffer

**Comment by LemonJuiz** [comment]
Also using the version from ticalc.org, if these have been fixed in the master branch I can test these scenarios again.

**Comment by mateoconlechuga** [comment]
Clearly you are not aware that only master branches have stable releases. The C version is on a separate branch and is currently in developement. You can find actual latest versions that fix all those bugs available here:

https://www.cemetech.net/programs/index.php?mode=file&id=1481

**Comment by PeterTillema** [comment]
Be sure to download the latest version [here](https://www.cemetech.net/programs/index.php?mode=file&path=/84pce/asm/ICECompiler.zip) before reporting bugs, because I've already fixed the bug that Output( stops the program :). Also, it seems you were compiling and running the C version of ICE? Because you talk about toString(, which is not implemented in both the ASM and the C version.
