### ISSUE TITLE
Display more routine calls in the [trace] menu.

### ISSUE THREAD

**Issue by SopaXorzTaker** [PeterTillema/ICE#25]
Currently, only 10 or so basic graphics routines are displayed, despite there being stored names for way more (for example, it'd recognize "det(76", but it's not in the menu).

Also, I'd like to suggest adding a keycode utility that would show the scancode of the currently pressed keyboard key - this would be a great aid, since one wouldn't have to look at the table every time.

**Comment by PeterTillema** [comment]
Press [LEFT] or [RIGHT] at the menu to get all the graphics command. I should make that more clear, because you were not the only one struggling with that.

Nice idea, I will see if that fits somehow in my cursor hook :)
