### ISSUE TITLE
Rand seed auto reset thingy

### ISSUE THREAD

**Issue by SanjivanM** [PeterTillema/ICE#49]
If I do this code: 

[i]RAND
Disp randInt(1,20
Pause

It (for me) always returns 17
I figured out that each time the compiled prgm is run, the rand seed is automatically reset, so it's like adding a 0->rand at the beginning of the SRC.  Can the randInt thing be made like TI-OS, where the rand seed isn't automatically reset? To expand on this, can the #->rand function be added?

**Comment by PeterTillema** [comment]
Fixed with d6205c6
