### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by Lucky4Luuk** [PeterTillema/ICE#53]
Please add proper list support soon!
I created lists in a TI-BASIC program, but using L6 froze up my TI-84-CE. Ram got cleared, sadly.

**Comment by PeterTillema** [comment]
Sorry, I'm not quite sure what you mean. ICE uses its own lists, and doesn't interfere with the OS lists at all.

**Comment by TheLastMillennial** [comment]
I'm sorry to hear that! I'm sure PT_ will have a fix soon. Meanwhile, to prevent RAM clears from hindering you again, I'd like to inform you about [Cesium](https://www.cemetech.net/programs/index.php?mode=file&id=1372). Cesium is a powerful shell that houses all of your programs under an easy to use app. It has useful features like searching for programs, and most importantly, a backup feature so you never have to worry about a RAM reset again! I made a video showcasing all of the backup features [here](https://www.youtube.com/watch?v=hZDzV1CDN3k).

**Comment by jcgter777** [comment]
@TheLastMillennial Stop advertising your video :P
