### ISSUE TITLE
suggestion: Arguments

### ISSUE THREAD

**Issue by SanjivanM** [PeterTillema/ICE#54]
can you make it so that `1:prgmARG` does one thing and `2:prgmARG` does something else?

`PROGRAM:ARGSRC`
`:If Ans=1`
`:Asm(FDCB24DE`
`:End`
`:If Ans=2`
`:Asm(FDCB0CE6`
`:End`
`:If Ans!=1 or Ans!=2`
`:Return`
`:End`

**Comment by PeterTillema** [comment]
Sounds fine to me. Will see what I can do
