### ISSUE TITLE
Add int(), ipart(), fpart() and expr()

### ISSUE THREAD

**Issue by LAX18** [PeterTillema/ICE#65]
I want to port a TI BASIC program that implements these commands but there is not good way to do it in ICE. Especially with floats coming to ICE, It would be great to have these decimal nullifying functions.

**Comment by PeterTillema** [comment]
int( and fPart( will be implemented indeed. expr( is way too hard to do; that means I have to include a full parser in the compiled program (you can't simply call ICE or something), so that's impossible.
