### ISSUE TITLE
Code for OS_Strings

### ISSUE THREAD

**Issue by Jaxder** [PeterTillema/ICE#69]
Interestingly enough, although both codes should work (I think), the second set of code does not work: 
```
sum(0
sum(2,'Str1',"w+",4->A
sum(4,"TICE",4,A
```

```
"TICE"->Str1
sum(0
sum(2,'Str1',"w+",4->A
sum(4,Str1,4,A
```

**Comment by PeterTillema** [comment]
Cannot reproduce, both work fine for me.
