### ISSUE TITLE
My program no longer works at all :'(

### ISSUE THREAD

**Issue by Pieman7373** [PeterTillema/ICE#7]
I had an older version of ICE (i'm not sure how old) and it didn't yet have the basic-subprogram feature implemented. So i just got the most recent version from Cemetech, and my program compiles fine, but it no longer runs correctly at all (even though i have not changed the source since i had the older version of ICE)

**Comment by PeterTillema** [comment]
What doesn't work anymore? Which piece of code?

**Comment by Pieman7373** [comment]
The whole thing compiles, but doesn't work any more, even after i take out
the portion that calls the basic sub-program...
It just does this, which I nothing like it uses to look 😂😂😂

**Comment by Pieman7373** [comment]
*which is nothing like it used to

**Comment by PeterTillema** [comment]
Okay, but still, what is your code? I can't check what is wrong without any piece of code :p

**Comment by Pieman7373** [comment]
I havent updated the pastebin in a while though...
I should probably move that onto github with the rest of the project
anyways 😂

**Comment by PeterTillema** [comment]
Looking at your code at https://pastebin.com/raw/zDaP6dW2, I get this results, which I'm not sure of it runs fine, but it definitely doesn't crash:
<img src="https://i.imgur.com/OWoldTr.png">

**Comment by Pieman7373** [comment]
Oh yeah, lol :
I'll have to add the ICE version to the github :D

**Comment by Pieman7373** [comment]
"Cuz thst's not quite what it looked like right before i got the new version of ICE :P

**Comment by AlvajoyAsante** [comment]
Graphic commands Dont work
