### ISSUE TITLE
Program size change

### ISSUE THREAD

**Issue by Ti64CLi** [PeterTillema/ICE#75]
The size of a program can change if an other program has been compiled before.
After deleting the first compiled program, and recompiling the second one, the size change too
That's so weird ^^

**Comment by LAX18** [comment]
I think I have run into this bug before, but I think I dismissed it.

**Comment by PeterTillema** [comment]
Probably because ICE doesn't clear the `reg` and `expr` structs, which means it still thinks a certain value is in a register, which would be automatically optimized. Do you mean compiling when returning to the homescreen after compiling the first one or restarting ICE at all?

**Comment by Ti64CLi** [comment]
Not restarting ice at all, only returning to the homescreen after compiling the first program
