### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Ti64CLi** [PeterTillema/ICE#78]
I can't compile this code :(
There are my errors : 
MAIN_CALC.C    (90,38) :       WARNING (197) No function prototype "ti_DetectAn
y" in scope
MAIN_CALC.C    (90,69) :       ERROR (152) Operands are not assignment compatib
le
make: *** [obj/main_calc.src] Error -1

**Comment by PeterTillema** [comment]
Update the toolchain and the libraries, they have been updated yesterday/tonight.

**Comment by LAX18** [comment]
Ah okay so ICE is now compatible with the latest version of the clibs?
