### ISSUE TITLE
Compiled Repo - ICE fails to find new labels

### ISSUE THREAD

**Issue by LAX18** [PeterTillema/ICE#81]
When I add labels to my ICE programs now, they fail to be detected by the compiler and the program is not compiled.

**Comment by PeterTillema** [comment]
Test

**Comment by PeterTillema** [comment]
I can't replicate this, since the Lbl/Goto test works fine. Do you have a minimal 'working' example for me to debug?

**Comment by PeterTillema** [comment]
Test

**Comment by LAX18** [comment]
I literally used this and it failed

[i]TEST1
Lbl TOP
Goto TOP

**Comment by PeterTillema** [comment]
Still can't replicate:
<img src="https://i.imgur.com/NquFZKp.png">

**Comment by LAX18** [comment]
Huh. It could be an issue with my calc. I recompiled ICE today and am having the same issue. I can attempt to get screenshots but I suspect this is an isolated incident relating to my calc.
Thanks for looking into this.

**Comment by PeterTillema** [comment]
Does it happen within CEmu or a real calculator?

**Comment by LAX18** [comment]
Real calculator. I did a complete memory wipe and reinstalled the OS and everything I had on it. The labels still do not find.
