### ISSUE TITLE
Cesium icons

### ISSUE THREAD

**Issue by SanjivanM** [PeterTillema/ICE#83]
When a program with an icon is compiled and run, it spits out random characters and quits.  Tested with v2.2 from Cemetech archives

**Comment by jcgter777** [comment]
Are you sure this isn't Cesium's problem?

**Comment by LAX18** [comment]
Huh, this seems to be a reoccuring issue. I personally, have experience a similar eent before with ICE.

I am using a custom built ICE so my confrimation is a bit off. My calc just immediatly stops the program, no weird text.

**Comment by SanjivanM** [comment]
@jcgter777 nope, even without Cesium, it does the same thing
