### ISSUE TITLE
Compiled Repo - Execution of Programs causes RAM Leak

### ISSUE THREAD

**Issue by LAX18** [PeterTillema/ICE#90]
I noticed in NOS that executing a programs makes ~20K bytes of RAM leak. I dont think this is an issue in my code, but it could very much be so, Mateo thought the ICE BASIC program execution code was buggy so I thought I would create this issue.

Thanks!

**Comment by LAX18** [comment]
Closed - User Error

**Comment by LAX18** [comment]
Oops. Mateo thinks it is an ICE problem after all, and my code should not cause issues.

**Comment by LAX18** [comment]
This code causes issues:
CloseAll
OpenVar(PROGRAM,"r",5)->PRGM
GetSize(PRGM)->SIZD
Alloc(SIZE)->DATA
Read(DATA,SIZE,1,PRGM)
Close(PRGM)
OpenVar("TEMP","w",5)->TEMP
Write('Asm(prgmASM'+"?"+'Return',9,1,SLOT)
Close(TEMP)
OpenVar("ASM","w",6)->ASM
Write(DATA,SIZE,1,ASM)
Close(ASM)
End()
Asm(CD3C1A02)
Asm(CD100802)
prgmTEMP
DeleteVar("TEMP,5)
DeleteVar("ASM",6)
CloseAll

**Comment by PeterTillema** [comment]
1) Use ``` to write down in Github issues.
2) Please double-check your code before sending it to me; what is `SIZE`? I only see `SIZD`. What is `End()`?
3) You don't need to Return yourself after executing a BASIC program.
4) It is indeed a user error; an assembly program start with the bytes `$EF $7B`, which aren't present in this case, thus throwing errors around. You should already know that ICE would silently ignore BASIC errors.
5) I can't replicate the ~20K memory leak, under the assumption that the program pointed to by `PROGRAM` actually exists, and neither `TEMP` nor `ASM` do.

**Comment by LAX18** [comment]
So I need to copy $EF7B to the beginning of the assembly program?

**Comment by LAX18** [comment]
Here is the leaking code:
`CloseAll()
OpenVar("TEMP","w",5")->SLOT
Write('Asm(prgm',3,1,SLOT)
Seek(3,0,SLOT)
Write(PROGRAM,length(PROGRAM),1,SLOT)
Close(SLOT)
Asm(CD3C1A02)
Asm(CD100802)
prgmTEMP
DeleteVar("TEMP",5
CloseAll`

**Comment by LAX18** [comment]
This is the code
`CloseAll()  
OpenVar("TEMP","w",5")->SLOT  
Write('Asm(prgm',3,1,SLOT)  
Seek(3,0,SLOT)  
Write(PROGRAM,length(PROGRAM),1,SLOT)  
Close(SLOT)  
Asm(CD3C1A02)  
Asm(CD100802)  
prgmTEMP  
DeleteVar("TEMP",5  
CloseAll`

**Comment by PeterTillema** [comment]
Tracked it down and figured out why; `asm_prgm_size` wasn't saved, and set to ~10 bytes when running the BASIC program, so instead of deleting NOS + C libs, it deleted about 10 bytes from UserMem, which isn't quite right :P However, it seems now it's leaking -2 bytes (it increases your amount of free memory somehow), so I will still open it.

**Comment by PeterTillema** [comment]
Well, I blame the OS; ICE/LibLoad code is fine.
