### ISSUE TITLE
No warning for invalid compiled program names

### ISSUE THREAD

**Issue by jcgter777** [PeterTillema/ICE#93]
When you make the compiled program name start with a number, after compiling, ICE will hide the program, and the new first char will also be invalid, so even when you unhide it, it will be hidden from the program list. If theres a space, it replaces it with ), which is valid, but it’s not what we want. Can there be a prompt when there’s an invalid char in the program name to rename the program? (And maybe have that change what’s in the source too)

**Comment by LAX18** [comment]
The space and ) issue has to do with ASCII codes. I see the value in this, but it seems a bit overboard.
