### ISSUE TITLE
Newest version will archive vars, but not unarchive them

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#94]
I downloaded ICE Compiler v2.2.0.0 and wrote a program in it, but it did not unarchive vars/programs. It did not throw an error, it ran normally, but it would not unarchive anything. Please tell me if this is just me, or if this is a real problem. If it is just me, please tell me how to fix it. Thank you.

**Comment by LAX18** [comment]
This is a bug with the C toolchain. This cannot be resolved by @PeterTillema

**Comment by calclover2514** [comment]
Okay. Thanks

**Comment by PeterTillema** [comment]
https://ufile.io/dgtp8 this is the latest ICE built from the source.

**Comment by calclover2514** [comment]
Thanks a million. I really appreciate it. This has fixed the problem I had with the ICE key hooks and the icon/description. However, it still will not UnArchive vars. By the way @LAX18, I have been informed that this is not a bug in the C toolchain.

**Comment by LAX18** [comment]
Huh. I raised this question a while ago and I could have sworn that was the conclusion.

**Comment by calclover2514** [comment]
I still do not have the newest icehooks appvar, so some of the features are still not working.
