### ISSUE TITLE
ICE won't fully install with newest release of C libraries

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#95]
ICE Compiler v2.2.0.0 will enable lowercase letters, but hitting the trace button does not open the extra menu and none of the token bytes are changed. Is this error caused by Cesium, or is it ICE itself?

**Comment by LAX18** [comment]
Did you send the ICEHOOKS.8xv to your calc? This holds all of the hooks. If the hooks are missing, this is most likely to blame.

**Comment by calclover2514** [comment]
I had the ICEHOOKS Appvar on my calc already. I tried resending it, but it still does not work.Perhaps a corrupted file is to blame?

**Comment by calclover2514** [comment]
I have solved the problem. The downloadable version of ICE does not support the newest C library update. I have downloaded an older version of the libraries, and ICE now works fine. Thank you

**Comment by calclover2514** [comment]
Using old C libraries has broken other programs now! Please fix ICE to work with new C libraries. Thanks

**Comment by PeterTillema** [comment]
I can't replicate this; I send the latest libraries to my calc, as well as the latest hook and the latest ICE (from the repo), and it works perfectly. Also, the hooks are not dependant of the C libraries, so I don't see what the issue is?

**Comment by PeterTillema** [comment]
Sorry, I didn't read carefully. ICE v2.2.0 is indeed broken, but it's quite "old" compared to this repo. I'm waiting for the debugger to be finished to release v2.3.0, so use the repo ICE for now!

**Comment by calclover2514** [comment]
OK Thanks!

**Comment by calclover2514** [comment]
I have tried to install the C SDK, but it will not work on my machine. Do you think you could build it and send me a link to it? Thanks.
