### ISSUE TITLE
Adding an icon and description will cause the program to quit working

### ISSUE THREAD

**Issue by calclover2514** [PeterTillema/ICE#96]
When I add an icon and description to certain ICE programs (possibly the ones using file I/O), the icon and description show up fine, but when I try to run it, it just gives me something like this and exits.
```
[]##!=#[.................Done
_$[a]ax!=[]###@%%^
```

**Comment by LAX18** [comment]
This is a well known issue. I would build the repo from the current source, then try. I know it was broke in a previous version, just unsure which one.

**Comment by calclover2514** [comment]
I do not have the capability to build from source. Hopefully this will be fixed soon! :) Thanks
