### ISSUE TITLE
SetTextScale only works once

### ISSUE THREAD

**Issue by SanjivanM** [PeterTillema/ICE#97]
When I use SetTextScale on a prgm, it only scales the text the first and maybe the second time that it's used.  I'll have to do some further testing, then I'll get code up.  I'm on mobile right now...

**Comment by runer112** [comment]
Being familiar with the underlying code for text scaling, I don't see any reason why it would only work for one or two text display calls. The setting should remain until you change it or the program exits.

**Comment by PeterTillema** [comment]
I need more code. Since this function works exactly like other functions, ICE-wise, I wonder whether this is the fault of ICE or not.

**Comment by SanjivanM** [comment]
I did more testing, and it seems that only AgendaCE code is what is doing this.  Ask @LAX18 for the SC link, I'm on mobile, I'll get the link if I get home before...

**Comment by LAX18** [comment]
This is the most recent link I have:

http://sc.cemetech.net/?hash=Dv/JvHg54qXKioSS/qhF8dJRFI21

**Comment by SanjivanM** [comment]
Yes, the version in the link is the version I used to test, I used ICE V2.2.1.0 to compile & run the code.

**Comment by PeterTillema** [comment]
Can you give me more information? What keys should I press to see the error? What is the expected output?

**Comment by SanjivanM** [comment]
On the first run, just set up some class names.  Close, then re run the program.  On the bottom of the screen that lists class names, there is a thing that says press mode to open the settings menu.  On the settings menu, the top that says "settings" or something like that should be 2x higher than normal, and the same width.  Press del to go to the deletion screen.  All the font there should be 1x width, 2x height.  Return as indicated, or delete the save files.  Hope this helps... I'm also on mobile right now, so sorry for the not so detailed information

**Comment by PeterTillema** [comment]
I've found the bug, but I can blame the toolchain. The problem is mainly that you call `det(0` twice, so if you remove the second (and eventually third) one, you will be good.
