### ISSUE TITLE
Compiled Repo 

### ISSUE THREAD

**Issue by LAX18** [PeterTillema/ICE#99]

**Comment by LAX18** [comment]
Oops. Cannot delete either.

Anyways building NOS is broke. The ICE compiler has display glitches and NOS RAM resets on run.
You can test by downloading the source branch and compiling NOSSRC http://www.github.com/LAX18/NOS

**Comment by jcgter777** [comment]
Are you sure it isn't NOS?

**Comment by LAX18** [comment]
There is no possible way. The output size is 61,159 or so bytes.

**Comment by jcgter777** [comment]
So? It could be broken?

**Comment by PeterTillema** [comment]
What kind of title is this?

**Comment by PeterTillema** [comment]
Fixed with 28a1f1e.
